<a href="https://colab.research.google.com/github/LiviaEmi/Importando-com-Git/blob/main/data_import.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Aula 1 - Python (27/05)**

- Importando dados de diferentes formatos do github

In [4]:
# importando dados do github

# 1ª maneira - baixar um repo para o colab
# !git clone <html>
# não é indicado, pq ele copia tudo do github

# 2ª maneira - importação via RAW
# importação unitária dos dados
# vai no github, abre cada arquivo, aperta em 'raw' e copia o link da página
# para arquiv do tipo xlsx, não precisa abrir o raw, só clica no arquivo >
# botão direito cabeçalho da pag > copiar link (arquivo 3)

arquivo1 = 'https://raw.githubusercontent.com/LiviaEmi/Importando-dados-com-Python/refs/heads/main/example_data.csv'
arquivo2 = 'https://raw.githubusercontent.com/LiviaEmi/Importando-dados-com-Python/refs/heads/main/example_data.json'
arquivo3 = 'https://github.com/LiviaEmi/Importando-dados-com-Python/raw/refs/heads/main/example_data.xlsx'
arquivo4 = 'https://raw.githubusercontent.com/LiviaEmi/Importando-dados-com-Python/refs/heads/main/sample_data.csv'

# para os csv - importar pandas
import pandas as pd
df_csv_exemple = pd.read_csv(arquivo1)
df_csv_sample = pd.read_csv(arquivo4)

# para o json
df_example_data = pd.read_json(arquivo2)
display(df_example_data)

# para o excel
# precisamos usar engine='openpyxl'
df_example_data_excel = pd.read_excel(arquivo3, engine='openpyxl')
display(df_example_data_excel)

      Name  Age  Score
0    Alice   23     88
1      Bob   34     92
2  Charlie   45     95
3    David   28     78
4      Eve   30     85

In [5]:
display(df_csv_exemple)

      Name  Age  Score
0    Alice   23     88
1      Bob   34     92
2  Charlie   45     95
3    David   28     78
4      Eve   30     85

In [6]:
display(df_csv_sample)

   id     name   age   department  salary
0   1    Alice  28.0  Engineering   75000
1   2      Bob   NaN        Sales   64000
2   3  Charlie  34.0           HR   72000
3   4    David  29.0  Engineering   69000
4   5      Eve   NaN    Marketing   60000

In [7]:
display(df_example_data)

                                           employees
0  {'name': 'Alice', 'age': 28, 'department': {'n...
1  {'name': 'Bob', 'age': 34, 'department': {'nam...
2  {'name': 'Charlie', 'age': 45, 'department': {...

In [8]:
display(df_example_data_excel)

      Name  Age  Score
0    Alice   23     88
1      Bob   34     92
2  Charlie   45     95
3    David   28     78
4      Eve   30     85

In [9]:
# ------- para deixar a tabela do json mais bonita visualmente -------
import pandas as pd
# requests: pega um valor da web
import requests

# importar o arquivo json para o sistema
arquivo2 = 'https://raw.githubusercontent.com/LiviaEmi/Importando-dados-com-Python/refs/heads/main/example_data.json'
resposta = requests.get(arquivo2)
# comando: vá até o github e pegue o conteúdo da URL
dados_arquivo2 = resposta.json()

df_json = pd.DataFrame(dados_arquivo2)
# agora vamos arrumar os dados para uma tabela

# comando try: parecido com o if, só que ele tenta até dar erro
try:
  tabela_dados = pd.json_normalize(dados_arquivo2['employees'])
  display(tabela_dados)

except KeyError:
  print('Não consigo ler o arquivo')

      name  age department.name department.role
0    Alice   28     Engineering       Developer
1      Bob   34           Sales         Manager
2  Charlie   45              HR       Recruiter