<a href="https://colab.research.google.com/github/LiviaEmi/Importando-com-Git/blob/main/Importando_com_Git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import unitário Github RAW

In [9]:
# ------- para deixar a tabela do json mais bonita visualmente -------
import pandas as pd
# requests: pega um valor da web
import requests

# importar o arquivo json para o sistema
url_raw = input('Cole o link do json aqui: ')
resposta = requests.get(url_raw)
# comando: vá até o github e pegue o conteúdo da URL
dados = resposta.json()

df_json = pd.DataFrame(dados)
# agora vamos arrumar os dados para uma tabela

# comando try: parecido com o if, só que ele tenta até dar erro
try:
  nome_tabela = input('Informe o nome da tabela: ')
  tabela_dados = pd.json_normalize(dados[nome_tabela]) # o nome da tabela tem q ser igual do arquivo
  display(tabela_dados)

except KeyError:
  print('Não consigo ler o arquivo')

Cole o link do json aqui: https://raw.githubusercontent.com/LiviaEmi/Importando-dados-com-Python/refs/heads/main/example_data.json
Informe o nome da tabela: employees

      name  age department.name department.role department.blablabla
0    Alice   28     Engineering       Developer               lalala
1      Bob   34           Sales         Manager                  NaN
2  Charlie   45              HR       Recruiter                  NaN

# Verificação dos dados

In [10]:
# Padronização das informações
tabela_dados['department.name'] = tabela_dados['department.name'].str.strip().str.upper()

# Para ver
print(tabela_dados['department.name'])

# Limpeza
# Apagar os dados que não quer exibir
tabela_dados = tabela_dados.drop(columns='department.blablabla')

0    ENGINEERING
1          SALES
2             HR
Name: department.name, dtype: object

In [11]:
# Renomear campos
tabela_dados = tabela_dados.rename(columns={
    "name": "Nome",
    "department.name": "Departamento",
    "department.role": "Função"
})

display(tabela_dados)

      Nome  age Departamento     Função
0    Alice   28  ENGINEERING  Developer
1      Bob   34        SALES    Manager
2  Charlie   45           HR  Recruiter